version: '3'
services:
  python:
    container_name: kq-backend
    environment:
      - FLASK_RUN_PORT=${PORT}
    build:
      context: .
    command: "flask --app app run --host 0.0.0.0 "
    ports:
      - ${PORT}:${PORT}